# Generated by Django 3.1 on 2022-09-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_varitaions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='varitaions',
            new_name='variations',
        ),
    ]
